test_that("running external solver works", {
  x <- c(1.2, 3.5, 10.6, 0.1, -2.3)
  precision <- 10
  rscript_path <- file.path(R.home(), "bin", "Rscript")
  solver_path <- file.path(find.package("solvergater"), "exec", "fake_simple.R")
  s <- extsolver_simple(paste(rscript_path, solver_path))
  old_wd <- getwd()
  setwd(tempdir())
  obj <- compute_objective(s, x, precision)
  expect_true(file.exists(s$value_file))
  expect_true(file.exists(s$gradient_file))
  setwd(old_wd)
  expect_length(obj$value, 1)
  expect_length(obj$gradient, length(x))
})
